[package]
name = "easee-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.23", features = [ "serde" ] }
leaky-bucket-lite = "0.5.2"
reqwest = { version = "0.11.14", default_features = false, features = [ "json", "rustls" ] }
serde = { version = "1.0.152", features = [ "derive" ] }
serde_json = "1.0.91"
